[package]
name = "rust_edge"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.8", features = ["transport"] }
tokio = { version = "1", features = ["full"] }
prost = "0.11"
prost-types = "0.11"
tokio-stream = "0.1"
