apiVersion: v1
kind: Service
metadata:
  name: agriml-service
spec:
  selector:
    app: agriml
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  - protocol: TCP
    port: 50052
    targetPort: 50052
  - protocol: TCP
    port: 50053
    targetPort: 50053
  type: LoadBalancer
